// Generated by scripts/generate-zstd-wasm.mjs — do not edit.
// Source: @bokuweb/zstd-wasm 0.0.27 (libzstd compiled to WebAssembly)

/** Names the binary exports its functions under, read from the shipped glue. */
export const ZSTD_WASM_EXPORTS = {
  "memory": "f",
  "callConstructors": "g",
  "isError": "h",
  "compressBound": "i",
  "compress": "m",
  "malloc": "s",
  "free": "t"
} as const;

/** Slots the binary expects its host functions in. */
export const ZSTD_WASM_IMPORTS = {
  "procExit": "a",
  "keepaliveClear": "b",
  "abort": "c",
  "setItimer": "d",
  "resizeHeap": "e"
} as const;
