template: "$CHANGES"

autolabeler:
  - label: "type/feature"
    title:
      - "/^feat(?:\\([a-z0-9][a-z0-9-]*\\))?!?: .+/"

  - label: "type/bug"
    title:
      - "/^fix(?:\\([a-z0-9][a-z0-9-]*\\))?!?: .+/"

  - label: "type/documentation"
    title:
      - "/^docs(?:\\([a-z0-9][a-z0-9-]*\\))?!?: .+/"

  - label: "type/dependencies"
    title:
      - "/^(?:chore|build)\\(deps\\)!?: .+/"

  - label: "type/maintenance"
    title:
      - "/^ci(?:\\([a-z0-9][a-z0-9-]*\\))?!?: .+/"
      - "/^perf(?:\\([a-z0-9][a-z0-9-]*\\))?!?: .+/"
      - "/^refactor(?:\\([a-z0-9][a-z0-9-]*\\))?!?: .+/"
      - "/^test(?:\\([a-z0-9][a-z0-9-]*\\))?!?: .+/"
      - "/^style(?:\\([a-z0-9][a-z0-9-]*\\))?!?: .+/"
      - "/^revert(?:\\([a-z0-9][a-z0-9-]*\\))?!?: .+/"
      - "/^chore(?:\\((?!deps\\))[a-z0-9][a-z0-9-]*\\))?!?: .+/"
      - "/^build(?:\\((?!deps\\))[a-z0-9][a-z0-9-]*\\))?!?: .+/"

  - label: "impact/breaking"
    title:
      - "/^[a-z]+(?:\\([a-z0-9][a-z0-9-]*\\))!: .+/"
